// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_flavour/environment.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (Environment.appFlavorName == "production") {
          return android;
        } else {
          return androidStag;
        }
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy_yhN2tShA5EyDG3JrpopoTHyNOgdB2g',
    appId: '1:5877375299:web:29f5f28da1ecf4d0860ff6',
    messagingSenderId: '5877375299',
    projectId: 'flavour-flutter',
    authDomain: 'flavour-flutter.firebaseapp.com',
    storageBucket: 'flavour-flutter.appspot.com',
    measurementId: 'G-8JY4CV0PES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDToY5aHK_W5EnkCsdFC7ivlqDQqmchQS0',
    appId: '1:5877375299:android:3f4d8c58adf54ca2860ff6',
    messagingSenderId: '5877375299',
    projectId: 'flavour-flutter',
    storageBucket: 'flavour-flutter.appspot.com',
  );

  static const FirebaseOptions androidStag = FirebaseOptions(
    apiKey: 'AIzaSyDToY5aHK_W5EnkCsdFC7ivlqDQqmchQS0',
    appId: '1:5877375299:android:f566683b79992a0f860ff6',
    messagingSenderId: '5877375299',
    projectId: 'flavour-flutter',
    storageBucket: 'flavour-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNqiFz0QL8SqtrCRXKvesob77HzU7kw8',
    appId: '1:5877375299:ios:2b61ef7302332ab5860ff6',
    messagingSenderId: '5877375299',
    projectId: 'flavour-flutter',
    storageBucket: 'flavour-flutter.appspot.com',
    iosBundleId: 'com.example.flutterFlavour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNqiFz0QL8SqtrCRXKvesob77HzU7kw8',
    appId: '1:5877375299:ios:7d2087240a0a5894860ff6',
    messagingSenderId: '5877375299',
    projectId: 'flavour-flutter',
    storageBucket: 'flavour-flutter.appspot.com',
    iosBundleId: 'com.example.flutterFlavour.RunnerTests',
  );
}
